apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: monitor-pool
  namespace: rook
spec:
  replicated:
    size: 1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: monitor-block
provisioner: rook.io/block
parameters:
  pool: replicapool
  clusterName: rook

